---
resource_types:
  - name: s3-iam
    type: docker-image
    source:
      repository: governmentpaas/s3-resource

resources:
  #- name: test_git
  #  icon: github-circle
  #  type: git
  #  source:
  #    branch: master
  #    #private_key: ((pipeline-git-priv-key))
  #    uri: git@github.com:gds-ahine/test-pipeline.git

  - name: upload_file_to_s3
    icon: file
    type: s3-iam
    source:
      bucket: ((readonly_private_bucket_name))
      region_name: eu-west-2
      versioned_file: test.txt

blocks:
  - config: &docker_config
      platform: linux
      image_resource:
        type: docker-image
        source:
            repository: gdscyber/concourse-worker-health
            tag: '1.2.8'


jobs:
  - name: s3_upload_test
    serial: true
    plan:
    - task: s3-upload-test-task
      config:
        <<: *docker_config
        outputs:
          - name: upload_file_to_s3
        run:
            path: bash
            args:
              - -c
              - |
                mkdir -p upload_file_to_s3
                echo 'Creating a testfile to upload to s3...'
                touch upload_file_to_s3/test.txt
                echo 's3 file test' > upload_file_to_s3/test.txt
                echo 'Uploading testfile to s3...'
    - put: upload_file_to_s3
      params:
        file: upload_file_to_s3/test.txt
        #on_success:
        #  task: check-file-uploaded-to-s3
        #  config:
          #        <<: *docker_config
          #        inputs:
          #          - name: upload_file_to_s3
          #        run:
          #          path: bash
          #          args:
          #            - -c
          #            - |
          #              pwd
          #              ls -l upload_file_to_s3


  - name: s3_download_test
    serial: true
    plan:
      - get: upload_file_to_s3
      - task: s3-download-test-task
        config:
          <<: *docker_config
          inputs:
            - name: upload_file_to_s3
          run:
            path: bash
            args:
              - -c
              - |
                aws s3 ls
                aws s3 rm s3://((readonly_private_bucket_name))/test.txt
                aws s3 ls
