---
resources:
  #- name: test_git
  #  icon: github-circle
  #  type: git
  #  source:
  #    branch: master
  #    #private_key: ((pipeline-git-priv-key))
  #    uri: git@github.com:gds-ahine/test-pipeline.git

  - name: test_s3_bucket
    type: s3
    source:
      bucket: ((readonly_private_bucket_name))
      regexp: (*).zip
      #regexp: directory_on_s3/release-(.*).tgz
      #access_key_id: ACCESS-KEY
      #secret_access_key: SECRET

blocks:
  - config: &docker_config
      platform: linux
      image_resource:
        type: docker-image
        source:
            repository: gdscyber/concourse-worker-health
            tag: '1.2.8'


jobs:
  - name: s3_test
    serial: true
    plan:
    #- get: test_git
    #  trigger: false
    - task: s3-test-task
      config:
        <<: *docker_config
        #inputs:
        #  - name: test_git
        #outputs:
        #  - name: s3_test_file
        #    path: ah_testfile/foo
        run:
            path: bash
            args:
              - -c
              - |
                echo 'Creating a testfile to upload to s3...'
                pwd
                touch test.zip
                echo 'Uploading testfile to s3...'
    - put: test_s3_bucket
      params:
        file: test.zip
