---
resources:

  - name: ah-test-repo
    icon: github-circle
    type: git
    source:
      uri: "https://github.com/gds-ahine/test-pipeline"
      branch: master
      #private_key: ((deploy-key))

blocks:
  - config: &ah_test_img

      platform: linux

      image_resource:
        type: docker-image
        source:
          repository: gdscyber/ah-test-image

jobs:
  - name: aaron_test_pipeline
    plan:
      - get: ah-test-repo
        trigger: false

      - task: test_task
        config:
          <<: *ah_test_img
          inputs:
          - name: ah-test-repo
          run:
            path: /bin/bash
            args:
              - -c
              - |
                echo "where is python..."
                which python
                echo "where is python3..."
                which python3
                echo "version of python3..."
                python3 -V
                echo "where is pip..."
                which pip
                echo "where is pip3..."
                which pip3
                pip install pipenv
                make test
                echo "testing if we are in a venv..."
                python3 venv_test.py
                echo "setting up a venv..."
                python3 -m venv venv
                echo "activating venv..."
                source venv/bin/activate
                echo "checking if were are now in a venv..."
                python3 venv_test.py
                #echo "installing pipenv via pip..."
                #pip install pipenv
                #echo "testing python3 lib install in venv..."
                echo "Tests complete."
            dir: ah-test-repo
