---
name: iam_lint_test

on:
  push:
    paths-ignore:
      - '**.md'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: xen0l/iam-lint@v1
      with:
        path: 'test_policies'
